updates:
- assignees: []
  commit-message:
    include: scope
    prefix: '[DEPENDENCY UPDATE]'
  directory: /
  labels:
  - dependencies
  open-pull-requests-limit: 10
  package-ecosystem: pip
  rebase-strategy: auto
  reviewers: []
  schedule:
    interval: daily
    time: 02:00
  security-updates: true
  versioning-strategy: increase
version: 2
